name: Build and Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}
  schedule:
    - cron: "0 20 * * *"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - name: Install DuckDB CLI
        run: |
          wget https://github.com/duckdb/duckdb/releases/download/v1.0.0/duckdb_cli-linux-amd64.zip -O duckdb_cli.zip
          unzip duckdb_cli.zip
          chmod +x duckdb
          mv duckdb /usr/local/bin
      - run: npm ci
      - run: npm run build
      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: fbe814d4a37d3d3d7fcfeec0ab929ff6
          projectName: filecoin-in-numbers
          directory: ./dist
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          branch: main
